# Generated by Django 5.2.5 on 2025-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalamount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
