# Generated by Django 5.2.5 on 2025-08-27 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_totalamount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalamount',
            new_name='total_amount',
        ),
    ]
